console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'FileBasedFindingsReport'

output-reports:
  active: true
  exclude:
    - 'TxtOutputReport'
    - 'XmlOutputReport'

comments:
  active: false

complexity:
  active: false

coroutines:
  active: false

empty-blocks:
  active: false

exceptions:
  active: false

formatting:
  active: true
  android: true
  ImportOrdering:
    active: false
    autoCorrect: false
  MaximumLineLength:
    active: true
    maxLineLength: 120
    excludes:
      - "**/test/**"
      - "**/androidTest/**"
      - "**/testFixtures/**"
      - "**/roboletricTest/**"
  Filename:
    active: false
  PackageName:
    active: false

naming:
  active: false

performance:
  active: false

potential-bugs:
  active: false

style:
  active: true
  UnusedParameter:
    active: false
  UnusedPrivateProperty:
    active: false
  ForbiddenImport:
    active: false
    imports: [ ]
    forbiddenPatterns: '(ktor.*|koin.*|kotlinx.datetime.*)'
  ForbiddenComment:
    active: true
    comments:
      - reason: 'Forbidden FIXME todo marker in comment, please fix the problem.'
        value: 'FIXME:'
      - reason: 'Forbidden STOPSHIP todo marker in comment, please address the problem before shipping the code.'
        value: 'STOPSHIP:'
    allowedPatterns: ''
  MaxLineLength:
    active: true
    maxLineLength: 120
    excludeCommentStatements: true
    excludes:
      - "**/test/**"
      - "**/androidTest/**"
      - "**/testFixtures/**"
      - "**/roboletricTest/**"
  UnnecessaryAbstractClass:
    active: true
    ignoreAnnotated:
      - Module
  MagicNumber:
    active: false
    excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**', '**/*.kts' ]
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
      - '0.2'
      - '1024'
  UnusedPrivateMember:
    active: true
    ignoreAnnotated:
      - 'Preview'
  ReturnCount:
    active: false

TwitterCompose:
  CompositionLocalAllowlist:
    active: false
    # You can optionally define a list of CompositionLocals that are allowed here
    # allowedCompositionLocals: LocalSomething,LocalSomethingElse
  CompositionLocalNaming:
    active: true
  ContentEmitterReturningValues:
    active: true
    # You can optionally add your own composables here
    # contentEmitters: MyComposable,MyOtherComposable
  ModifierComposable:
    active: true
  ModifierMissing:
    active: true
  ModifierReused:
    active: true
  ModifierWithoutDefault:
    active: true
  MultipleEmitters:
    active: true
    # You can optionally add your own composables here
    # contentEmitters: MyComposable,MyOtherComposable
  MutableParams:
    active: true
  ComposableNaming:
    active: true
    # You can optionally disable the checks in this rule for regex matches against the composable name (e.g. molecule presenters)
    # allowedComposableFunctionNames: .*Presenter,.*MoleculePresenter
  ComposableParamOrder:
    active: true
  PreviewNaming:
    active: true
  PreviewPublic:
    active: true
    # You can optionally disable that only previews with @PreviewParameter are flagged
    # previewPublicOnlyIfParams: false
  RememberMissing:
    active: true
  UnstableCollections:
    active: true
  ViewModelForwarding:
    active: false
  ViewModelInjection:
    active: true
